Run Report 13:03 08/25/2020
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'requests.exceptions.ChunkedEncodingError'>, ChunkedEncodingError(ProtocolError("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), <traceback object at 0x000001EC8F9879C0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'requests.exceptions.ChunkedEncodingError'>, ChunkedEncodingError(ProtocolError("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), <traceback object at 0x000001EC8FC13280>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'requests.exceptions.ChunkedEncodingError'>, ChunkedEncodingError(ProtocolError("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), <traceback object at 0x000001EC8FDF9340>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'requests.exceptions.ChunkedEncodingError'>, ChunkedEncodingError(ProtocolError("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), <traceback object at 0x000001EC8FB092C0>)Run Report 14:57 08/25/2020Run Report 15:39 08/25/2020
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D6077FC1C0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D6078E3340>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60A95A740>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D6078FD3C0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D607987340>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D6078D5940>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60AAB3340>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D606F9FB80>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60795C440>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60A99FB80>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60994C280>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D606F85DC0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60A9A0C00>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D609964CC0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60ACB8300>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60ADD2E40>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60ACD7980>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60ACEB740>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60AEAE1C0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D606F17A40>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60994FD80>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'requests.exceptions.ChunkedEncodingError'>, ChunkedEncodingError(ProtocolError("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), <traceback object at 0x000001D606F42D40>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60AD14780>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x000001D60ADA1CC0>)Run Report 17:21 08/25/2020
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020206AFA900>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020206BF71C0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020209C5E780>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020206BBDDC0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020209D392C0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020206C24AC0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020209E85AC0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020206222B80>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x00000202062A7FC0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020209C49E80>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020206C19C80>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020206C8B9C0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000002020627E840>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020206267E00>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020209F81B00>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000002020A00D980>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020208C62980>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020209FE9D00>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000002020A2BF9C0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000020209FBFC80>)Run Report 18:25 08/25/2020
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'requests.exceptions.ChunkedEncodingError'>, ChunkedEncodingError(ProtocolError("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), <traceback object at 0x000001711F5CB540>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'requests.exceptions.ChunkedEncodingError'>, ChunkedEncodingError(ProtocolError("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), <traceback object at 0x000001711F41D6C0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'requests.exceptions.ChunkedEncodingError'>, ChunkedEncodingError(ProtocolError("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), <traceback object at 0x000001711C2FDDC0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=1&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'find_all'"), <traceback object at 0x000001711C25EA40>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=2&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'requests.exceptions.ConnectionError'>, ConnectionError(ProtocolError('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))), <traceback object at 0x000001711F35F2C0>)
Error: DataFirst https://www.datafirst.uct.ac.za/dataportal/index.php/catalog#_r=&collection=&country=&dtype=2&from=1947&page=3&ps=&sk=&sort_by=nation&sort_order=&to=2019&topic=&view=s&vk=: (<class 'requests.exceptions.ChunkedEncodingError'>, ChunkedEncodingError(ProtocolError("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), <traceback object at 0x000001711F528B00>)Number of Hits: 318
Number of Requests: 318
Hit Rate: 1.0Datafiles downloaded: 0Run finished 12:29 08/26/2020